import React, { Suspense, lazy } from 'react';
import type { Metadata } from "next";
const Sidebar = lazy(() => import('@/components/Sidebar'));
const NavigationBar = lazy(() => import('@/components/NavigationBar'));
const Container = lazy(() => import('@/components/Container'));
import './globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
    <Suspense fallback={<div>Loading...</div>}>    
        <div className="flex h-screen">
          <Sidebar />          
          <Container className="flex-1 flex flex-col bg-gray-50">
          <Suspense fallback={<div>Loading Navigation...</div>}>
            <NavigationBar />
          </Suspense>
            {children}
          </Container>
        </div>      
    </Suspense>
    </body>
    </html>
  );
}
